### ISSUE TITLE
Imprecision in date time values

### ISSUE THREAD

**Issue by avivace** [gbdev/database#260]
If the "most accurate" information we have regarding the release date of an entry is something like "2009" or "August 2009", how do we save it? Should we allow "imprecise" date time values to avoid having to reduce those to 1/1/2009 and 8/2009?

**Comment by dag7dev** [comment]
I think the safest choice is:
- every "August 2009" -> 2009-08
- every unspecified date, let's just assume 01 --> 2009-08-01

Is it accurate? We don't have further data, and rather than unstructured data, we might prefer to have a semi-consistent representation. In case dates become more clear, they can be fixed.

**Comment by avivace** [comment]
>     * every "August 2009" -> 2009-08

This is currently not accepted by the schema,  hence why I opened this issue

> every unspecified date, let's just assume 01 --> 2009-08-01

this "assumption" is actually introducing even more noise/imprecision to the data, it's the same question as writing 2,00 and 2, they mean different things and imply different precision. a `2009-08-01` would now be indistinguishable from a "real" entry that was released on that day.
